# Generated by Django 2.2.13 on 2022-04-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0007_auto_20181115_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='created_from',
            field=models.CharField(default='IE', max_length=100),
        ),
    ]
