# Generated by Django 2.2.13 on 2022-04-12 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0008_voucher_created_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='max_discount_value',
            field=models.FloatField(blank=True, null=True, verbose_name='Max Discount'),
        ),
    ]
