# Generated by Django 2.2.13 on 2022-07-05 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0009_voucher_max_discount_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='max_discount_value',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Max Discount'),
        ),
    ]
