# Generated by Django 2.2.13 on 2022-06-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotp',
            name='purpose',
            field=models.CharField(blank=True, choices=[('MV', 'Mobile Verification'), ('LO', 'Login')], default='MV', max_length=2, null=True),
        ),
    ]
