# Generated by Django 2.2.13 on 2022-07-19 07:21

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220611_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.get_profile_picture, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['JPEG', 'PNG', 'JPG'])], verbose_name='Profile Picture'),
        ),
    ]
