# Generated by Django 2.2.13 on 2021-06-17 07:05

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0010_auto_20210413_1756'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='Order number')),
                ('amount', models.FloatField(default=0, verbose_name='Amount')),
                ('rz_order_id', models.CharField(max_length=100, unique=True)),
                ('rz_payment_id', models.CharField(max_length=100, unique=True)),
                ('razorpay_signature', models.TextField(null=True)),
                ('rz_response', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('P', 'Paid'), ('F', 'Fail'), ('C', 'Created')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_transaction', to='order.Order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_transaction', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
