# Generated by Django 2.2.9 on 2020-01-22 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0016_auto_20190327_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='home_with_product',
            field=models.BooleanField(default=False, verbose_name='Show on home with product'),
        ),
        migrations.AddField(
            model_name='category',
            name='home_with_subcategory',
            field=models.BooleanField(default=False, verbose_name='Show on home with subcategory'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Featured'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Featured'),
        ),
    ]
