# Generated by Django 2.2.9 on 2020-02-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0019_bannerimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_new_arrival',
            field=models.BooleanField(default=False, verbose_name='Add in New Arrival'),
        ),
    ]
