# Generated by Django 2.2.9 on 2020-02-07 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0020_product_is_new_arrival'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='name')),
                ('hex_code', models.CharField(max_length=7, verbose_name='hex code')),
            ],
        ),
    ]
