# Generated by Django 2.2.9 on 2020-02-11 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0023_auto_20200211_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ForeignKey(blank=True, help_text='If you are adding variants of this product. then you dont need to add color of this product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalogue.Color'),
        ),
    ]
