# Generated by Django 2.2.9 on 2020-11-10 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0024_auto_20200211_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='home_with_product',
        ),
        migrations.RemoveField(
            model_name='category',
            name='home_with_subcategory',
        ),
    ]
