# Generated by Django 2.2.9 on 2020-11-10 07:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0025_auto_20201110_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_new_arrival',
        ),
        migrations.AddField(
            model_name='product',
            name='additional_information',
            field=models.TextField(blank=True, verbose_name='Additional Information'),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_information',
            field=models.TextField(blank=True, verbose_name='Delivery Information'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_add_to_gallery',
            field=models.BooleanField(default=False, verbose_name='Add to Gallery Section'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_add_to_insta_eats',
            field=models.BooleanField(default=False, verbose_name='Add to InstaEats Section'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Add to Popular Products'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_rating',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Add to Featured Products'),
        ),
    ]
