# Generated by Django 2.2.9 on 2020-11-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0026_auto_20201110_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerimages',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Subtitle'),
        ),
    ]
