# Generated by Django 2.2.9 on 2020-11-19 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0027_bannerimages_subtitle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_featured',
        ),
    ]
