# Generated by Django 2.2.9 on 2020-11-28 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0028_auto_20201119_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Suggested Image Size is 1920x766', max_length=255, null=True, upload_to='categories', verbose_name='Image'),
        ),
    ]
