# Generated by Django 2.2.13 on 2021-04-15 04:54

import catalogue.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0032_product_is_latest_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=catalogue.models.get_category_icon_path, verbose_name='Icon'),
        ),
    ]
