# Generated by Django 2.2.13 on 2021-06-29 08:35

import catalogue.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0033_category_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTestimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('customer_image', models.ImageField(blank=True, null=True, upload_to=catalogue.models.get_customer_testimonial_path, verbose_name='Customer Image')),
                ('review', models.TextField(verbose_name='Review')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
            ],
        ),
    ]
