# Generated by Django 2.2.13 on 2022-05-11 11:18

import catalogue.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0035_category_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietitionsAndNutritionists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30, null=True, verbose_name='Title')),
                ('image', models.ImageField(blank=True, null=True, upload_to=catalogue.models.get_dietitians_image_path, verbose_name='Image')),
                ('url', models.URLField(blank=True, null=True, verbose_name='HyperLink')),
                ('dietitions_and_nutritionists', models.CharField(choices=[('Testimonial', ' Testimonial'), ('Follower', 'Follower')], max_length=30, verbose_name='Dietitions And Nutritionists')),
            ],
        ),
    ]
