# Generated by Django 2.2.13 on 2022-05-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0040_auto_20220519_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tagline',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Tagline'),
        ),
    ]
