# Generated by Django 2.2.13 on 2022-06-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0042_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='delivery_information',
        ),
        migrations.AddField(
            model_name='product',
            name='benefits',
            field=models.TextField(blank=True, null=True, verbose_name='Benefits'),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.TextField(blank=True, null=True, verbose_name='Ingredients'),
        ),
    ]
