# Generated by Django 2.2.13 on 2022-06-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0043_auto_20220624_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_rating_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Rating Count'),
        ),
    ]
