# Generated by Django 2.2.13 on 2022-07-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0047_auto_20220628_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='user_name',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Anonymous User Name (If user not selected)'),
        ),
    ]
