# Generated by Django 2.2.13 on 2022-07-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0048_productreview_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Anonymous User Email (If user not selected)'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='user_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Anonymous User Name (If user not selected)'),
        ),
    ]
