# Generated by Django 2.2.13 on 2022-07-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0049_auto_20220701_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unboxing_video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Unboxing Video Url'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Anonymous Email (If user not selected)'),
        ),
    ]
