# Generated by Django 2.2.13 on 2022-07-07 06:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0050_auto_20220705_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta Keywords'), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Meta Title'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_slug',
            field=models.SlugField(blank=True, max_length=300, null=True, unique=True, verbose_name='Product Slug'),
        ),
    ]
