# Generated by Django 2.2.13 on 2022-07-07 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0051_auto_20220707_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_slug',
        ),
    ]
