# Generated by Django 2.2.13 on 2022-07-12 12:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0052_remove_product_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='meta_keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=list, max_length=200, verbose_name='Meta Keywords'), blank=True, null=True, size=None),
        ),
    ]
