# Generated by Django 2.2.13 on 2022-07-23 10:14

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0054_auto_20220712_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='customertestimonial',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonial_product', to='catalogue.Product'),
        ),
        migrations.AddField(
            model_name='dietitionsandnutritionists',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dietitions_product', to='catalogue.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta Keywords'), blank=True, null=True, size=None),
        ),
    ]
