# Generated by Django 2.2.13 on 2022-07-23 11:46

import catalogue.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0055_auto_20220723_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_benefit_image',
            field=models.ImageField(blank=True, help_text='Suggested size 379x197px for dietitians and Suggested size 326x379 px for followers', null=True, upload_to=catalogue.models.get_product_benefit_image_path, verbose_name='Product Benefit Image'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_description',
            field=models.TextField(blank=True, null=True, verbose_name='Product Description'),
        ),
    ]
