# Generated by Django 2.2.13 on 2022-07-28 11:38

import catalogue.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0057_faqs'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_banner_image',
            field=models.ImageField(blank=True, help_text='Suggested size 379x197px for dietitians and Suggested size 326x379 px for followers', null=True, upload_to=catalogue.models.get_banner_image_path, verbose_name='Product Banner Image'),
        ),
    ]
