# Generated by Django 2.2.13 on 2022-08-03 06:56

import catalogue.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0058_product_product_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='thumbnail_image',
            field=models.ImageField(blank=True, help_text='Suggested Image Size is 1920x766', null=True, upload_to=catalogue.models.get_review_image_path, verbose_name=' Video Image'),
        ),
    ]
