# Generated by Django 2.2.13 on 2022-08-16 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0060_questionaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionaire',
            name='age',
            field=models.CharField(blank=True, choices=[('0-16', '0-16'), ('17-40', '17-40'), ('41-70', '41-70'), ('71-100', '71-100')], max_length=10, null=True, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='questionaire',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True, verbose_name='Gender'),
        ),
    ]
