# Generated by Django 2.2.13 on 2022-08-17 04:52

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0061_auto_20220816_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionaire',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address'),
        ),
        migrations.AddField(
            model_name='questionaire',
            name='mobile_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Mobile Number'),
        ),
        migrations.AddField(
            model_name='questionaire',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Full Name'),
        ),
    ]
