# Generated by Django 2.2.13 on 2022-08-17 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0062_auto_20220817_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_benefit_1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Product Benefit One'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_benefit_2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Product Benefit 2'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_tagline',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Product Tagline'),
        ),
        migrations.AlterField(
            model_name='questionaire',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True, verbose_name='Gender'),
        ),
    ]
