# Generated by Django 2.2.13 on 2022-08-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0063_auto_20220817_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Product Title'),
        ),
    ]
