# Generated by Django 2.2.13 on 2022-08-31 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0064_product_product_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='program_detail',
            field=models.TextField(blank=True, null=True, verbose_name='Program Detail'),
        ),
    ]
