# Generated by Django 2.2.13 on 2022-09-29 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0066_auto_20220915_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='diet_modification_donts',
            field=models.TextField(blank=True, null=True, verbose_name="Diet Modification Dont's"),
        ),
        migrations.AddField(
            model_name='product',
            name='diet_modification_dos',
            field=models.TextField(blank=True, null=True, verbose_name="Diet Modification Do's"),
        ),
        migrations.AddField(
            model_name='product',
            name='lifestyle_modification_donts',
            field=models.TextField(blank=True, null=True, verbose_name="Lifestyle Modification Dont's"),
        ),
        migrations.AddField(
            model_name='product',
            name='lifestyle_modification_dos',
            field=models.TextField(blank=True, null=True, verbose_name="Lifestyle Modification Do's"),
        ),
        migrations.AddField(
            model_name='product',
            name='nutritional_recommendation',
            field=models.TextField(blank=True, null=True, verbose_name='Nutritional Recommendation'),
        ),
    ]
