# Generated by Django 2.2.13 on 2022-11-10 10:10

import catalogue.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0067_auto_20220929_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.TextField(blank=True, null=True, verbose_name='Heading')),
                ('title', models.TextField(blank=True, null=True, verbose_name='Title')),
                ('image', models.ImageField(blank=True, null=True, upload_to=catalogue.models.get_dietitians_image_path, verbose_name='Image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_section', to='catalogue.Product')),
            ],
        ),
    ]
