# Generated by Django 2.2.13 on 2022-10-19 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0068_auto_20221019_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='show_in_subscription_plan',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subscription_ordering',
        ),
    ]
