# Generated by Django 2.2.13 on 2022-11-10 11:18

import catalogue.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0068_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='product',
        ),
        migrations.AlterField(
            model_name='section',
            name='image',
            field=models.ImageField(blank=True, help_text='Suggested size 379x197px for dietitians and Suggested size 326x379 px for followers', null=True, upload_to=catalogue.models.get_blog_image_path, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Title'),
        ),
    ]
