# Generated by Django 2.2.13 on 2022-11-10 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0069_auto_20221110_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_product', to='catalogue.Product'),
        ),
    ]
