# Generated by Django 2.2.13 on 2022-11-11 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0070_section_product'),
        ('catalogue', '0070_auto_20221019_1051'),
    ]

    operations = [
    ]
