# Generated by Django 2.2.13 on 2022-11-14 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0075_remove_blog_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='How_it_work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=60, null=True, verbose_name='Title')),
                ('heading', models.TextField(blank=True, null=True, verbose_name='Heading')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='how_it_work_product', to='catalogue.Product')),
            ],
        ),
    ]
