# Generated by Django 2.2.13 on 2022-11-14 11:13

import catalogue.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0077_auto_20221114_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='how_it_work',
            name='image',
            field=models.ImageField(blank=True, help_text='Suggested size 379x197px for dietitians and Suggested size 326x379 px for followers', null=True, upload_to=catalogue.models.get_blog_image_path, verbose_name='Image'),
        ),
    ]
