# Generated by Django 2.2.13 on 2022-11-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0080_remove_middle_heading1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='middle',
            name='heading',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Heading'),
        ),
    ]
