# Generated by Django 2.2.13 on 2022-11-14 12:54

import catalogue.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0083_auto_20221114_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.FileField(blank=True, help_text='Suggested size 379x197px for dietitians and Suggested size 326x379 px for followers', null=True, upload_to=catalogue.models.get_blog_image_path, verbose_name='Image'),
        ),
    ]
