# Generated by Django 2.2.13 on 2022-11-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0093_auto_20221115_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Title'),
        ),
    ]
