# Generated by Django 2.2.13 on 2022-11-15 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0094_auto_20221115_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='how_it_work',
            name='main_title',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Main_Title'),
        ),
    ]
