# Generated by Django 2.2.13 on 2022-11-15 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0096_section_main_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='middle',
            name='main_heading',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Main_Heading'),
        ),
    ]
