# Generated by Django 2.2.13 on 2022-11-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0099_auto_20221115_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietitionsandnutritionists',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='HyperLink'),
        ),
    ]
