# Generated by Django 2.2.13 on 2022-11-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0100_auto_20221115_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='url',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Url'),
        ),
    ]
