# Generated by Django 2.2.13 on 2022-11-15 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0101_auto_20221115_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='middle',
            name='main_heading',
        ),
    ]
