# Generated by Django 2.2.13 on 2022-11-16 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0103_auto_20221115_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='Micronutrientdeficiency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Heading')),
                ('description', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='micronutrient_product', to='catalogue.Product')),
            ],
        ),
        migrations.DeleteModel(
            name='Middle',
        ),
    ]
