# Generated by Django 2.2.13 on 2022-11-16 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0106_auto_20221116_1248'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menu',
            new_name='Our_products',
        ),
    ]
