# Generated by Django 2.2.13 on 2022-11-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0110_auto_20221116_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='who_we_are',
            name='Hyperlink',
        ),
        migrations.AddField(
            model_name='who_we_are',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Url'),
        ),
    ]
