# Generated by Django 2.2.13 on 2022-11-16 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0113_faqsproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqs',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faqs_product', to='catalogue.Product'),
        ),
    ]
