# Generated by Django 2.2.13 on 2022-11-17 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0114_auto_20221116_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faqs',
            name='timestamp',
        ),
    ]
