# Generated by Django 2.2.13 on 2022-11-17 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0115_remove_faqs_timestamp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FAQS',
        ),
    ]
