# Generated by Django 2.2.13 on 2022-11-17 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0116_delete_faqs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Question')),
                ('answer', models.CharField(blank=True, max_length=10000, null=True, verbose_name='Answer')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_product', to='catalogue.Product')),
            ],
        ),
    ]
