# Generated by Django 2.2.13 on 2022-11-17 10:17

import catalogue.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0117_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Suggested size 379x197px for dietitians and Suggested size 326x379 px for followers', null=True, upload_to=catalogue.models.get_about_us_image_path, verbose_name='Image')),
                ('title', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('our_vision', models.CharField(choices=[('Our mission', 'Our mission'), ('Our vision ', 'Our vision')], max_length=30, verbose_name='Our_vision')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_us_product', to='catalogue.Product')),
            ],
        ),
    ]
