# Generated by Django 2.2.13 on 2022-11-17 11:19

import catalogue.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0119_faqicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqicon',
            name='image',
            field=models.ImageField(blank=True, help_text='Suggested size 379x197px for dietitians and Suggested size 326x379 px for followers', null=True, upload_to=catalogue.models.get_faqicon_image_path, verbose_name='Image'),
        ),
    ]
