# Generated by Django 2.2.13 on 2022-11-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0120_auto_20221117_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqicon',
            name='step',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Step'),
        ),
        migrations.AlterField(
            model_name='faqicon',
            name='title',
            field=models.CharField(blank=True, max_length=20000, null=True, verbose_name='Title'),
        ),
    ]
