# Generated by Django 2.2.13 on 2022-11-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0122_auto_20221117_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frame4',
            name='description',
        ),
        migrations.AddField(
            model_name='frame4',
            name='description1',
            field=models.TextField(blank=True, null=True, verbose_name='Description1'),
        ),
        migrations.AddField(
            model_name='frame4',
            name='description2',
            field=models.TextField(blank=True, null=True, verbose_name='Description2'),
        ),
        migrations.AddField(
            model_name='frame4',
            name='description3',
            field=models.TextField(blank=True, null=True, verbose_name='Description3'),
        ),
        migrations.AddField(
            model_name='frame4',
            name='description4',
            field=models.TextField(blank=True, null=True, verbose_name='Description4'),
        ),
    ]
