# Generated by Django 2.2.13 on 2022-11-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0125_auto_20221117_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame5',
            name='choice',
            field=models.CharField(choices=[('Our mission', 'our mission'), ('Our vision ', 'our vision')], max_length=30, verbose_name='Choice'),
        ),
    ]
