# Generated by Django 2.2.13 on 2022-11-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0127_auto_20221117_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame5',
            name='choice',
            field=models.CharField(choices=[(1, 'Our_mission'), (2, 'Our_vision')], max_length=30, verbose_name='Choice'),
        ),
    ]
