# Generated by Django 2.2.13 on 2022-11-18 10:45

import catalogue.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0130_auto_20221118_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame1',
            name='frames',
            field=models.CharField(blank=True, choices=[('Frame 1', 'Frame 1'), ('Frame 2', 'Frame 2'), ('Frame 3', 'Frame 3'), ('Frame 4', 'Frame 4'), ('Frame 5', 'Frame 5')], max_length=30, null=True, verbose_name='Frames'),
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, help_text='Suggested size 379x197px for dietitians and Suggested size 326x379 px for followers', null=True, upload_to=catalogue.models.get_header_image_path, verbose_name='Image')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title')),
                ('icon', models.CharField(blank=True, max_length=100, null=True, verbose_name='Icon')),
                ('hyperlink', models.URLField(blank=True, null=True, verbose_name='Hyperlink')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='header_product', to='catalogue.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, help_text='Suggested size 379x197px for dietitians and Suggested size 326x379 px for followers', null=True, upload_to=catalogue.models.get_header_image_path, verbose_name='Image')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title')),
                ('links', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Links')),
                ('icon', models.CharField(blank=True, max_length=100, null=True, verbose_name='Icon')),
                ('hyperlink', models.URLField(blank=True, null=True, verbose_name='Hyperlink')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='footer_product', to='catalogue.Product')),
            ],
        ),
    ]
