# Generated by Django 2.2.13 on 2021-07-02 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0006_auto_20181115_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='address_type',
            field=models.CharField(choices=[('HM', 'Home Address'), ('OF', 'Office Address'), ('BH', 'Brothers Home')], default='HM', max_length=5, verbose_name='Address Type'),
        ),
    ]
