# Generated by Django 2.2.13 on 2021-07-02 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0007_useraddress_address_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='address_type',
            field=models.CharField(choices=[('HM', 'Home Address'), ('OF', 'Office Address'), ('OTH', 'Other')], default='HM', max_length=5, verbose_name='Address Type'),
        ),
    ]
