# Generated by Django 2.2.13 on 2022-08-23 08:51

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0008_auto_20210702_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='alternate_mobile_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Alternate Mobile Number'),
        ),
    ]
