# Generated by Django 2.2.13 on 2022-09-19 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0009_useraddress_alternate_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
    ]
