MEDICAL_CONDITION = (
    ('Thyroid', 'Thyroid'),
    ('Diabetes', 'Diabetes'),
    ('PCOD', 'PCOD'),
    ('Heart diseases', 'Heart Diseases'),
    ('Digestive Issues', 'Digestive Issues'),
    ('Skin Problems', 'Skin Problems'),
    ('Constipation', 'Constipation'),
    ('Acidity', 'Acidity'),
    ('Hyperpigmenation', 'Hyperpigmenation'),
)

SYMPTOMS_CHOICES = (
    ('Confusion', 'Confusion (Unable to foccus on thing)'),
    ('Fatigue', 'Fatigue'),
    ('Exhaustion', 'Exhaustion'),
    ('Tiredness and Sleepiness', 'Tiredness and Sleepiness'),
    ('Anemia', 'Anemia or Lack of Red Blood Cells'),
    ('coldness', 'coldness'),
    ('Burning or sore tongue', 'Burning or sore tongue'),
    ('Cravings for non-nutritive substances', 'Cravings for non-nutritive substances, such as ice, dirt or starch'),
    ('Craving for Sugar', 'Craving for Sugar'),
    ('Irregular hunger feeling', 'Irregular hunger feeling '),
    ('Muscle cramps', 'Muscle cramps'),
    ('Frequent Sweating', 'Frequent  Sweating'),
    ('Irregular Heartbeat', 'Irregular Heartbeat (slow or fast)'),
    ('Feeling Bloated', 'Feeling Bloated'),
    ('Nervousness', 'Nervousness'),
    ('Cracked lips', 'Cracked lips'),
    ('Dry skin', 'Dry skin'),
    ('Hair loss', 'Hair loss'),
    ('Slow wound Healing', 'Slow wound Healing (slower recovery of any injury like cut, bruise, lesion)'),
    ('Nose bleeding', 'Nose bleeding'),
    ('Cramps in legs and muscles', 'Cramps in legs and muscles'),
    ('Pain and Weakness in Muscles', 'Pain and Weakness in Muscles'),
    ('Feeling of Depression, Anxiety, Stress', 'Feeling of Depression, Anxiety, Stress'),
    ('Joint Pain', 'Joint Pain (knee, ankle, wrist, elbow, hip)'),
    ('Hairfall', 'Hairfall'),
    ('Sensitive Skin and Acne', 'Sensitive Skin and Acne'),
    ('Loss of Appetite', 'Loss of Appetite'),
    ('Loss of taste', 'Loss of taste'),
    ('Dry & Damaged hair', 'Dry & Damaged hair'),
    ('Brittle Nails', 'Brittle Nails ( Nails breaking easily)'),
    ('Craving for Snacks', 'Craving for Snacks'),
    ('Early graying of hair', 'Early graying of hair'),
    ('Loss of Libido', 'Loss of Libido (lack of sex drive)'),
    ('Weakness', 'Weakness'),
    ('Irritabilty', 'Irritabilty (Mood Swings)'),
)