# Generated by Django 2.2.13 on 2021-04-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_surcharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_done',
            field=models.BooleanField(default=False, verbose_name='Payment Done'),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
