# Generated by Django 2.2.13 on 2021-03-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0008_auto_20181115_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date Updated'),
        ),
    ]
